### ISSUE TITLE
Out of sync with temporal upstream

### ISSUE THREAD

**Issue by robholland** [coinbase/temporal-ruby#11]
I've sent quite a few PRs but keep finding more things out of sync with upstream so I'm going to stop with the PRs until the examples run cleanly. Just wanted add a note here to say I'm working on it.

Feel free to close the other PRs and wait for a larger one which gets the examples running.

The specs have drifted a lot due to change from cadence and thrift to temporal so short term I don't expect to adjust those or get them running but happy to fix those up after the examples run.

**Comment by henghonglee** [comment]
![image](https://user-images.githubusercontent.com/906931/96368702-eb3f8d80-1187-11eb-9259-1941e5eeb68b.png)
Hi! I was exploring and trying to run the examples and found that some of the paths were wrong. pasting them here in case anyone needs these changes. :)

**Comment by robholland** [comment]
https://github.com/clearbit/temporal-ruby/tree/rh-main is my dev branch for the work in case anyone wants to see what's up.

**Comment by antstorm** [comment]
@robholland sounds great, thank you for your help! I suggest getting the most basic example working first and then progressing incrementally to keep PRs small and allow others to contribute

**Comment by robholland** [comment]
The PR needed to get the simple example passing was still pretty large, splitting into smaller PRs over the next few days.
