### ISSUE TITLE
Add RubyDoc.info hook

### ISSUE THREAD

**Issue by antstorm** [coinbase/temporal-ruby#115]
@DeRauk can you please raise a ticket with Infra (I don't have access) to add a `https://www.rubydoc.info/checkout` webhook to this repo? This will make sure that our documentation gets updated automatically when we merge PRs.

**Comment by antstorm** [comment]
Btw, you can ask for the same hook for the `cadence-ruby` repo to avoid back-n-forth

**Comment by DeRauk** [comment]
This should be done.

**Comment by antstorm** [comment]
Perfect, thank you very much! 👍
