### ISSUE TITLE
Invalid argument for string field 'name' (given String)

### ISSUE THREAD

**Issue by haimgel** [coinbase/temporal-ruby#123]
Very strange results when starting a workflow defined elsewhere. Minimal demo:
```ruby
irb(main):001:0> require 'temporal'
=> true
irb(main):002:0> Temporal.start_workflow('HelloWorldWorkflow')
/Users/haim/Projects/personal/temporal-ruby/lib/temporal/connection/grpc.rb:89:in `initialize': Invalid argument for string field 'name' (given String). (Google::Protobuf::TypeError)
	from /Users/haim/Projects/personal/temporal-ruby/lib/temporal/connection/grpc.rb:89:in `new'
	from /Users/haim/Projects/personal/temporal-ruby/lib/temporal/connection/grpc.rb:89:in `start_workflow_execution'
	from /Users/haim/Projects/personal/temporal-ruby/lib/temporal/client.rb:49:in `start_workflow'
```

**If I freeze this workflow name string or pass a symbol, it works as expected!** E.g. this works:
```ruby
Temporal.start_workflow('HelloWorldWorkflow'.freeze)
```

I see this happening with Ruby 3.0.2 and 2.6.5. 
My dependencies are:
```
  specs:
    google-protobuf (3.19.1-x86_64-darwin)
    googleapis-common-protos-types (1.3.0)
      google-protobuf (~> 3.14)
    grpc (1.41.1-universal-darwin)
      google-protobuf (~> 3.17)
      googleapis-common-protos-types (~> 1.0)
    oj (3.13.9)

PLATFORMS
  x86_64-darwin-20
```

**Comment by antstorm** [comment]
@haimgel sorry for a long delay, this somehow slipped through the cracks (feel free to ping us again if this ever happens again).

It's a nasty issue, glad that you've raised it. Here's a fix and an explanation — https://github.com/coinbase/temporal-ruby/pull/128

**Comment by haimgel** [comment]
Wow, this is indeed a weird issue! Glad you were able to get to the bottom of it. I can confirm, it works fine now (in your branch).

**Comment by antstorm** [comment]
@haimgel brilliant, thank you for confirming!

I've merged the PR and also [reported the issue](https://bugs.ruby-lang.org/issues/18428) to Ruby devs, very curious what's their take on it
