### ISSUE TITLE
ProtoJSONPayload support

### ISSUE THREAD

**Issue by stuppy** [coinbase/temporal-ruby#191]
Go impl: https://github.com/temporalio/sdk-go/blob/master/converter/proto_json_payload_converter.go

Today, if a proto Message is passed as a payload, the JSON to_payload `Temporal::JSON.serialize(data)` into what looks like the proto class descriptor and not the data within the message.

**Comment by antstorm** [comment]
This issue can probably be closed now

**Comment by stuppy** [comment]
https://github.com/coinbase/temporal-ruby/pull/192 indeed! 🙇
