### ISSUE TITLE
ArgumentError: wrong number of arguments (given 2, expected 4)

### ISSUE THREAD

**Issue by Draiken** [coinbase/temporal-ruby#245]
#234 introduced a bug here: https://github.com/coinbase/temporal-ruby/blob/41a8e923e52f62a6727e3ce6ffa2d68090b29439/lib/temporal/workflow/context.rb#L116

We introduced 2 new arguments to activity contexts and this code-path is not properly using them.

The error happens inside of a method that has `TODO: how to handle failures?` on top of it, which I'm guessing is masking the failure on the specs.

If possible I'd add documentation to not use `execute_locally` outside of tests. This method caused issues for us before due to the lack of proper error handling.

**Comment by jeffschoner** [comment]
@DeRauk PR is out for this one. This is breaking all local activity usage in workflows, so high priority for review and merging.
