### ISSUE TITLE
Use Keyword Arguments in Activities

### ISSUE THREAD

**Issue by santiagodoldan** [coinbase/temporal-ruby#248]
Hello, first of all, thank you for creating this gem, it works great 🙌 

I would like to use keyword arguments in some of my activity classes, that would look like 👇 

```
class MyActivity < Temporal::Activity
  def execute(foo:)
    ...
  end
end
```

Based on my research we could support keyword arguments by changing this method -> https://github.com/coinbase/temporal-ruby/blob/master/lib/temporal/activity.rb#L12 (we are only using the splat operator for arrays), maybe a callable class as here https://github.com/dry-rb/dry-transaction/blob/main/lib/dry/transaction/callable.rb could help to cover all the different ways of calling an activity.

I'm open to working on a PR if the idea makes sense.

Bests

**Comment by arrowcircle** [comment]
Hey! You can look at what I came with: typed input and output https://github.com/coinbase/temporal-ruby/issues/244

**Comment by santiagodoldan** [comment]
@arrowcircle that seems interesting, thanks for sharing 💯 

I pushed a small PR that should add support for keyword args -> https://github.com/coinbase/temporal-ruby/pull/255

**Comment by arrowcircle** [comment]
@santiagodoldan This is a great improvement! For me, it's more consistent and useful to use typed input/output, but just because I already implemented it :)
