### ISSUE TITLE
uninitialized constant Temporal::Metadata::DECISION_TYPE

### ISSUE THREAD

**Issue by kittrCZ** [coinbase/temporal-ruby#26]
Hello,

there is still one instance of `Temporal::Metadata::DECISION_TYPE` in `temporal-ruby/lib/temporal/workflow/task_processor.rb:32` and due to that the examples are not working correctly.

**Comment by antstorm** [comment]
@kittrCZ the latest rename PR probably missed it. Would you might opening a PR with your change?

**Comment by antstorm** [comment]
Nevermind, just found the PR. Thank you 👍

**Comment by kittrCZ** [comment]
No problem; Glad I could help! Good job on the lib. It's delight to work with Ruby on that 👍

**Comment by antstorm** [comment]
@kittrCZ thank you, glad you like it 🎉
