### ISSUE TITLE
Unable to connect to temporal cloud

### ISSUE THREAD

**Issue by jsonck** [coinbase/temporal-ruby#260]
Based on the Temporal cloud [SSL certificate generation guidelines](https://docs.temporal.io/cloud/certificates#:~:text=How%20to%20issue%20root%20CA%20and%20end%2Dentity%20certificates%E2%80%8B
), I ran the following two commands to create the certs:

`tcld gen ca --org temporal -d 1y --ca-cert ca.pem --ca-key ca.key`

`tcld gen leaf --org temporal -d 364d --ca-cert ca.pem --ca-key ca.key --cert client.pem --key client.key`

These commands created four files: 
- ca.key
- ca.pem
- client.key
- client.pem

I uploaded the ca.key into my temporal cloud's namespace. The other files were used in the initializer code as follows: 

```
require 'temporal-ruby'

root_cert = File.read("./ssl/ca.pem")
client_key = File.read("./ssl/client.key")
client_chain = File.read("./ssl/client.pem")

Temporal.configure do |config|
  config.host = 'rvapp.o5nlk.tmprl.cloud'
  config.port = 7233
  config.namespace = 'rvapp.o5nlk'
  config.task_queue = 'hello-world'
  config.credentials = GRPC::Core::ChannelCredentials.new(root_cert, client_key, client_chain)
end

Temporal.list_namespaces page_size: 10
```

The error I'm receiving on my local machine when running the code above:
```
 Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
```

If anyone could point me in the right direction it would be greatly appreciated!

**Comment by jsonck** [comment]
Resolved. I needed to use `nil` in place of the root cert. 

`GRPC::Core::ChannelCredentials.new(nil, client_key, client_chain)`

**Comment by realflash7** [comment]
@jsonck Any specific reason you are using `nil` for root_cert?

you can find root_cert as server certificate by

```
openssl s_client -connect <your namespace gRPC endpoint>
```
