### ISSUE TITLE
How to trigger external workflow, or make an activities for external workflow (defined in different SDK)

### ISSUE THREAD

**Issue by khangvo88** [coinbase/temporal-ruby#271]
Hello, 

I am trying to writing a Ruby Temporal activity that works with an (external) workflow defined in a different micro-service (writing Typescript SDK). When a Temporal server tries to pick up the activity from same queue, I have a issue "Workflow is not registered with this worker"
It seems that an activity forced to be defined inside Ruby's Workflow, which we not want. What is the appropriate way to do it?

Also if I want to trigger any external workflow, which the current micro-service does not hold ownership for that workflow, what is the appropriate way to trigger it. 
Compared to [temporalio/ruby-sdk](https://github.com/temporalio/sdk-ruby), it claims support "Starting a workflow (defined in any other SDK)", e.g. 
```
# Start a workflow
handle = client.start_workflow('MyWorkflow', 'some input', id: 'my-id', task_queue: 'my-task-queue')
```

How we can achieve the same with this SDK?

Thanks in advance.

**Comment by DeRauk** [comment]
Hi, sorry for the delay here. You shouldn't be getting that error in your workflow if you're only registering activities, if you're still having trouble can you reply with how you're starting your worker and registering your activities?

For your second question, I don't think we have an example in the repo but you can specify the name of a workflow to start by setting the `name` property on options. [Link](https://github.com/coinbase/temporal-ruby/blob/95d62d239448cb062994006be335e00c2d028db4/lib/temporal/execution_options.rb#L10)

**Comment by khangvo88** [comment]
thanks for your clear response.
