### ISSUE TITLE
Sync Activity is named as AsyncAcitivity in the examples

### ISSUE THREAD

**Issue by subintp** [coinbase/temporal-ruby#283]
Here AsyncActivity is called in a blocking fashion. But the workflow is named as AsyncActivityWorkflow

```
require 'activities/async_activity'

class AsyncActivityWorkflow < Temporal::Workflow
  def execute
    AsyncActivity**.execute!**
  end
end
```

**Comment by DeRauk** [comment]
The async naming here is referring to the activity, which will not complete until it is signaled by an external event. See https://github.com/coinbase/temporal-ruby?tab=readme-ov-file#asynchronous-completion
