### ISSUE TITLE
Middleware documentation

### ISSUE THREAD

**Issue by davidcelis** [coinbase/temporal-ruby#287]
Hiya! Is there any chance you could add a section on your README about middleware in the Temporal Ruby SDK? We're looking to add some exception logging to our workflows/activities but there's just not a lot of clarity on how to effectively implement and add middleware or what information is available to middleware. For example, when would you add middleware to the activity middleware stack or the workflow stack (or both)? And what's the difference between "workflow middleware" and "workflow task middleware?

**Comment by DeRauk** [comment]
Sure, PR is up here: https://github.com/coinbase/temporal-ruby/pull/288
