### ISSUE TITLE
Temporal::Client::get_workflow_history does not fetch complete history due to pagination

### ISSUE THREAD

**Issue by cduanfigma** [coinbase/temporal-ruby#289]
The method as-is doesn't use the `next_page_token` in the response to continue fetching results: https://github.com/coinbase/temporal-ruby/blob/c4fb094638c85289c16b4611c3432f759cfb13a8/lib/temporal/client.rb#L400-L408

I'm thinking of opening a PR to rewrite this to paginate and get the complete history like how it's done in `fetch_full_history` here. Just wanted to check if there were any objections. 

https://github.com/coinbase/temporal-ruby/blob/c4fb094638c85289c16b4611c3432f759cfb13a8/lib/temporal/workflow/task_processor.rb#L103-L119

**Comment by DeRauk** [comment]
@cduanfigma Thank you for the PR! I left some comments.
