### ISSUE TITLE
Is it possible to call a workflow with named parameters

### ISSUE THREAD

**Issue by ajdevries** [coinbase/temporal-ruby#62]
When triggering a workflow with a hash, it is not possible to use named parameters.

Looks like the call in the dispatcher:
- https://github.com/coinbase/temporal-ruby/blob/master/lib/temporal/workflow/dispatcher.rb#L16

is splatting up the hash. Example:

```
response = client.start_workflow_execution(
      ...
      input: {param1: 'value', param2: 'value'},
      ...
    )

...
class SomeWorkflow < Temporal::Workflow

  def execute(param1:, param2:)
  end
end
```

Not sure if this is possible and wanted?

**Comment by antstorm** [comment]
@ajdevries this should work. I tried modifying the `examples/workflows/cancelling_timer_workflow.rb` example to have:

```ruby
...
def execute(activity_timeout:, timer_timeout:)
...
```

and then called it via:

```ruby
Temporal.start_workflow(CancellingTimerWorkflow, activity_timeout: 2, timer_timeout: 4)
```

and everything worked as expected. Bear in mind that `client.start_workflow_execution` that you're using is a low-level API and is not a public interface.

**Comment by ajdevries** [comment]
Hi @antstorm thanks for the quick response. I think you're right. I used the low-level API because I'm not certain if all workflows that we use are defined in Ruby (maybe some are defined in other languages).

But this makes sense, closing this issue for now, thanks for the feedback and suggestions
