### ISSUE TITLE
SSL Support for GRPC Client

### ISSUE THREAD

**Issue by tristan-instacart** [coinbase/temporal-ruby#70]
Hello.

I have prepared a local branch with SSL support and updated documentation for using it. In my use case we deployed in AWS and needed to run SSL on our load balancer to the frontend service. I was unable to push the branch and open the PR however. 

I'd be happy to open a PR for the change, it's actually fairly simple. 

Additionally, is this SDK going to get revamped to support the Rust based SDK core? Obviously my SSL changes would need some revision if that were the case. 

Thank you for all the work you've put in so far, it's been very helpful to have this SDK out there!

**Comment by antstorm** [comment]
@tristan-instacart glad you're enjoying the SDK!

Feel free to fork the repo and submit a PR via your fork (very common approach in open source, here's a tutorial — https://www.dataschool.io/how-to-contribute-on-github/). I did a test implementation of the SSL at some point, but please feel free to contribute yours as I might not have the time to get to submitting mine this week.

We are not yet planning to switch to using the core SDK, as it's probably still months away. With this in mind an interim SSL solution for the current version would be great

**Comment by jlemesh** [comment]
@tristan-instacart I'll continue if you don't mind.

**Comment by antstorm** [comment]
@tristan-instacart any chance we can finish this one and merge it?
