### ISSUE TITLE
Unexpected non-determinism error when using timers 

### ISSUE THREAD

**Issue by jeffschoner-stripe** [coinbase/temporal-ruby#75]
I'm running into an unexpected non-determinism error. 

### Repro steps
1. Modify the `CancellingTimerWorkflow` to be:
```
class CancellingTimerWorkflow < Temporal::Workflow
  def execute(activity_timeout, timer_timeout)
    activity_future = SleepActivity.execute(activity_timeout)
    timer = workflow.start_timer(timer_timeout)
    timer.done do
      if !activity_future.finished?
        HelloWorldActivity.execute!('reminder')
      end
    end

    activity_future.wait
    timer.cancel
    HelloWorldActivity.execute!('done')
  end
end
```
This change is on the latest commit of https://github.com/jeffschoner-stripe/temporal-ruby/tree/non-determinism-repro if you'd prefer to check out the branch.

2. Execute the workflow with an `activity_timeout` less than the `timer_timeout` such that the timer will be canceled. E.g.,
```
examples/bin/trigger CancellingTimerWorkflow 5 15
```

### Expected Behavior
`SleepActivity` completes after 5 seconds, timer gets canceled, workflow completes successfully

### Observed behavior
`SleepActivity` completes after 5 seconds, but the workflow task fails with a message of "Unexpected command cancel_timer_request"

Captured history (JSON and screenshot) of my execution of this workflow:
[workflow history JSON export](https://github.com/coinbase/temporal-ruby/files/6511994/dfad7d5b.a1c5.4a62.b935.6d8645714d04.-.eac20293-b4cd-41a7-a81f-b9a507769f14.txt)

![Screen Shot 2021-05-19 at 16 33 38](https://user-images.githubusercontent.com/63118764/118898223-ecbd6980-b8c0-11eb-802f-7e7917a1306b.png)

### Other Notes
- Originally, I was seeing this when the `SleepActivity` was replaced by an asynchronously completed activity, but that does not seem to matter as it reproduces with both kinds of activities. The sleep is easier to execute than triggering the async complete.
- If the `activity_timeout` is larger than the `timer_timeout`, the workflow executes as expected. The timer fires before the `SleepActivity` has completed, its block executes, and the timer is canceled once the activity does complete.

**Comment by antstorm** [comment]
I believe this is now fixed
