### ISSUE TITLE
`namespace` and `task-queue` metric tags are inconsistently used

### ISSUE THREAD

**Issue by anantag** [coinbase/temporal-ruby#90]
`namespace` and `task-queue`tags are not passed here https://github.com/coinbase/temporal-ruby/blob/master/lib/temporal/workflow/task_processor.rb#L27 but are passed https://github.com/coinbase/temporal-ruby/blob/master/lib/temporal/workflow/poller.rb#L65

Given that these are primitive tags, we should be passing them consistently for any metric. 

In general, I think it would be good to define a static tag list somewhere that can be used across all metrics.

**Comment by antstorm** [comment]
That's a great spot! Would you be up for drafting a PR to fix this discrepancy?

**Comment by jverce** [comment]
@DeRauk since there's a PR open to address this issue, can we get a maintainer to review/approve it?

PS: I'm not sure what's the best way to notify the maintainers in general, sorry for tagging you directly but you're the maintainer that approved the latest merged PR 😛

**Comment by DeRauk** [comment]
Hey @jverce, I've asked the PR author to rebase and resolve conflicts and then I can merge.

Sorry for the delay, I typically respond faster to tags in the Temporal Slack group, but directly tagging me here is fine too.
